### ISSUE TITLE
Feature/Compatibility Request - Blacklist Lootr Chests from respawning

### ISSUE THREAD

**Issue by katubug** [someaddons/respawningstructures#1]
Hi! I'm a modpack maker and server admin, and I'm delighted to discover this mod, as it will be a great tool!

However, combining it with lootr is a little overpowered, as all players can get loot from every structure every 48 hours. I would love the ability to blacklist certain blocks (such as the lootr chests) from respawning. Right now it respawns loot in non-lootr inventories, and I think that's totally okay. It's specifically ONLY the lootr chests which I want to leave in their default state. Even if that means a player can break them and they won't respawn.

Is this something that is feasible to do? Thank you so much for your time!

**Comment by someaddons** [comment]
Hi, that'd need to be done on Lootr's side, since my mod is simply asking the structure to place again, I dont have control over what happens during the placement.

I do think however that your're probably overestimating the impact of lootr chests respawning in dungeons, as to really abusive it players would need to make a very coordinated effort to clear structures and respawn them and collectively raid them right after the respawns.

During gameplay I think structure respawns won't be this visible that players can directly act on them, as the timer also does reset anytime a player changes something in a structure, and normally players won't know that they're respawning ever X hours (can also vary it in the config away from the default 48h)

If despite that players actually collectively come together to "farm dungeons" every reset it might even be a positive thing overall, because there is little reason in minecraft for them to work together like this so it'd probably be a great thing for the servers community overall.
