### ISSUE TITLE
Not issue but question...

### ISSUE THREAD

**Issue by AnyankaT** [someaddons/respawningstructures#2]
I'm pre-generating a server world with a number of different structure mods and using Respawning Structures in order for the players to have more access to dungeons. My question is this: If I manually delete a structure from the world, or it doesn't spawn on worldgen because I have that structure mod temporarily turned off, will Respawning Structures "regenerate" it anyway? 

I don't want a bunch of unintended structures popping up, and I don't know exactly how your mod works. I'm very excited about using it on our world, though!

**Comment by someaddons** [comment]
if the mod generating the structure is not installed the it literally does not exist and can't be picked up at all, even if added later.
Now dungeons which are manually removed do get detected, and may respawn potentially.
(You could avoid that by blacklisting or placing a bunch of blocks by hand in addition to removing the dungeon)

For your usecase of pregenerating it is not needed that respawning dungeons mod is present while you're preparing the world though, you only need to add it once you want it to start tracking structures and changes to them. So you can just prepare the world without the mod, manually modifying as you like, and then adding it once players start playing

**Comment by GlitchedGekko** [comment]
I'd like to understand the conditions required for a structure to regenerate/respawn. Because I've done some minor testing with an ancient city where I've set the timer as low as possible (1 min) and raided some chests, then left the structure and came back. When checking the status the mod says that structure's reset timer is over but the structure is not being reset. Is it that I need to leave the structure zone for it to reset? Or do I need to unload all the chunks? I'd just like to know what conditions I have to fulfill in order to proc "this structure will now respawn"
